### ISSUE TITLE
Check Japanese translations

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/EnableWindowsLogSettings#1]
document  translate to japanese

2022/09/29 TOC

- [x] [Author](https://github.com/Yamato-Security/EnableWindowsLogSettings#author)
- [x] [Acknowledgements](https://github.com/Yamato-Security/EnableWindowsLogSettings#acknowledgements)
- [x] [Problems with the default Windows log settings](https://github.com/Yamato-Security/EnableWindowsLogSettings#problems-with-the-default-windows-log-settings)
- [x] [Warning: Use at your own risk!](https://github.com/Yamato-Security/EnableWindowsLogSettings#warning-use-at-your-own-risk)
- [x] [Important Windows event logs](https://github.com/Yamato-Security/EnableWindowsLogSettings#important-windows-event-logs)
  - [x] [Sigma's top log sources](https://github.com/Yamato-Security/EnableWindowsLogSettings#sigmas-top-log-sources)
    - [x] [Top sigma log sources](https://github.com/Yamato-Security/EnableWindowsLogSettings#top-sigma-log-sources)
    - [x] [Top Security Event IDs](https://github.com/Yamato-Security/EnableWindowsLogSettings#top-security-event-ids)
- [x] [Increasing the maximum file size](https://github.com/Yamato-Security/EnableWindowsLogSettings#increasing-the-maximum-file-size)
  - [x] [Option 1: Manually through Event Viewer](https://github.com/Yamato-Security/EnableWindowsLogSettings#option-1-manually-through-event-viewer)
  - [x] [Option 2: Windows built-in tool](https://github.com/Yamato-Security/EnableWindowsLogSettings#option-2-windows-built-in-tool)
  - [x] [Option 3: PowerShell](https://github.com/Yamato-Security/EnableWindowsLogSettings#option-3-powershell)
  - [x] [Option 4: Group Policy](https://github.com/Yamato-Security/EnableWindowsLogSettings#option-4-group-policy)
- [x] [Configuration script](https://github.com/Yamato-Security/EnableWindowsLogSettings#configuration-script)
- [x] [Configuring log settings](https://github.com/Yamato-Security/EnableWindowsLogSettings#configuring-log-settings)
  - [x] [Sysmon log (1382 sigma rules)](https://github.com/Yamato-Security/EnableWindowsLogSettings#sysmon-log-1382-sigma-rules)
  - [x] [Security log (1045 sigma rules (903 process creation rules + 142 other rules))](https://github.com/Yamato-Security/EnableWindowsLogSettings#security-log-1045-sigma-rules-903-process-creation-rules--142-other-rules)
  - [x] [Powershell logs (175 sigma rules)](https://github.com/Yamato-Security/EnableWindowsLogSettings#powershell-logs-175-sigma-rules)
    - [x] [Module logging (30 sigma rules)](https://github.com/Yamato-Security/EnableWindowsLogSettings#module-logging-30-sigma-rules)
      - [x] [Enabling module logging](https://github.com/Yamato-Security/EnableWindowsLogSettings#enabling-module-logging)
        - [x] [Option 1: Enabling through group policy](https://github.com/Yamato-Security/EnableWindowsLogSettings#option-1-enabling-through-group-policy)
        - [x] [Option 2: Enabling through the registry](https://github.com/Yamato-Security/EnableWindowsLogSettings#option-2-enabling-through-the-registry)
    - [x] [Script Block Logging (134 sigma rules)](https://github.com/Yamato-Security/EnableWindowsLogSettings#script-block-logging-134-sigma-rules)
      - [x] [Enabling Script Block logging](https://github.com/Yamato-Security/EnableWindowsLogSettings#enabling-script-block-logging)
        - [x] [Option 1: Enabling through group policy](https://github.com/Yamato-Security/EnableWindowsLogSettings#option-1-enabling-through-group-policy-1)
        - [x] [Option 2: Enabling through the registry](https://github.com/Yamato-Security/EnableWindowsLogSettings#option-2-enabling-through-the-registry-1)
    - [x] [Transcription logging](https://github.com/Yamato-Security/EnableWindowsLogSettings#transcription-logging)
      - [x] [Enabling Transcription logging](https://github.com/Yamato-Security/EnableWindowsLogSettings#enabling-transcription-logging)
        - [x] [Option 1: Enabling through group policy](https://github.com/Yamato-Security/EnableWindowsLogSettings#option-1-enabling-through-group-policy-2)
        - [x] [Option 2: Enabling through the registry](https://github.com/Yamato-Security/EnableWindowsLogSettings#option-2-enabling-through-the-registry-2)
    - [x] [References](https://github.com/Yamato-Security/EnableWindowsLogSettings#references)
  - [x] [System log (55 sigma rules)](https://github.com/Yamato-Security/EnableWindowsLogSettings#system-log-55-sigma-rules)
  - [x] [Application log (16 sigma rules)](https://github.com/Yamato-Security/EnableWindowsLogSettings#application-log-16-sigma-rules)
  - [x] [Windows Defender Operational log (10 sigma rules)](https://github.com/Yamato-Security/EnableWindowsLogSettings#windows-defender-operational-log-10-sigma-rules)
  - [x] [Bits-Client Operational log (6 sigma rules)](https://github.com/Yamato-Security/EnableWindowsLogSettings#bits-client-operational-log-6-sigma-rules)
  - [x] [Firewall log (6 sigma rules)](https://github.com/Yamato-Security/EnableWindowsLogSettings#firewall-log-6-sigma-rules)
  - [x] [NTLM Operational log (3 sigma rules)](https://github.com/Yamato-Security/EnableWindowsLogSettings#ntlm-operational-log-3-sigma-rules)
  - [x] [Security-Mitigations KernelMode and UserMode logs (2 sigma rules)](https://github.com/Yamato-Security/EnableWindowsLogSettings#security-mitigations-kernelmode-and-usermode-logs--2-sigma-rules)
  - [x] [PrintService logs (2 sigma rules)](https://github.com/Yamato-Security/EnableWindowsLogSettings#printservice-logs-2-sigma-rules)
    - [x] [Admin (1 sigma rule)](https://github.com/Yamato-Security/EnableWindowsLogSettings#admin-1-sigma-rule)
    - [x] [Operational (1 sigma rule)](https://github.com/Yamato-Security/EnableWindowsLogSettings#operational-1-sigma-rule)
  - [x] [SMBClient Security log (2 sigma rules)](https://github.com/Yamato-Security/EnableWindowsLogSettings#smbclient-security-log-2-sigma-rules)
  - [x] [AppLocker logs (1 sigma rule)](https://github.com/Yamato-Security/EnableWindowsLogSettings#applocker-logs-1-sigma-rule)
  - [x] [CodeIntegrity Operational log (1 sigma rule)](https://github.com/Yamato-Security/EnableWindowsLogSettings#codeintegrity-operational-log-1-sigma-rule)
  - [x] [Diagnosis-Scripted Operational log (1 sigma rule)](https://github.com/Yamato-Security/EnableWindowsLogSettings#diagnosis-scripted-operational-log-1-sigma-rule)
  - [x] [DriverFrameworks-UserMode Operational log (1 sigma rule)](https://github.com/Yamato-Security/EnableWindowsLogSettings#driverframeworks-usermode-operational-log--1-sigma-rule)
  - [x] [WMI-Activity Operational log (1 sigma rule)](https://github.com/Yamato-Security/EnableWindowsLogSettings#wmi-activity-operational-log--1-sigma-rule)
  - [x] [TerminalServices-LocalSessionManager Operational log (1 sigma rule)](https://github.com/Yamato-Security/EnableWindowsLogSettings#terminalservices-localsessionmanager-operational-log--1-sigma-rule)
  - [x] [TaskScheduler Operational log (1 sigma rule)](https://github.com/Yamato-Security/EnableWindowsLogSettings#taskscheduler-operational-log--1-sigma-rule)

**Comment by hitenkoku** [comment]
@YamatoSecurity  日本語のドキュメントを確認しました。少し、手直ししたほうが良さそうなところを修正して #3 でpull-requestを出しておきました。ご確認のほどよろしくお願いいたします。

**Comment by YamatoSecurity** [comment]
@hitenkoku ありがとうございました！
https://github.com/Yamato-Security/EnableWindowsLogSettings/blob/main/ConfiguringSecurityLogAuditPolicies-Japanese.md　の和訳ができたので、それもお願いできますか？
(sigma ruleとdescriptionはまだ残っていますが、取り敢えず英語のままで良いかなと思っています）

**Comment by hitenkoku** [comment]
@YamatoSecurity  遅くなり申し訳ございません。
#5 で少し翻訳と日本語の修正をpull-requestで出しておきました。問題がなければマージをお願いいたします。
#5 がマージされたらこちらのissueはcloseしてもよろしいでしょうか？

**Comment by YamatoSecurity** [comment]
はい、修正のPRありがとうございました！
大変助かりました。
