### ISSUE TITLE
Batch file: category or subcategory?

### ISSUE THREAD

**Issue by LasseKrache** [Yamato-Security/EnableWindowsLogSettings#4]
Hello,

Just starting to take a deeper look at this amazing project, but stumbled about this:
Is it possible, that you have to change the following commands in your batch file form "/category" to "/subcategory"?
At least I receive corresponding error messages when I try to run them ...

```
:: Account Management
:::: Computer Account Management
auditpol /set /category:{0CCE9236-69AE-11D9-BED3-505054503030} /success:enable /failure:enable
:::: Other Account Management Events
auditpol /set /category:{0CCE923A-69AE-11D9-BED3-505054503030} /success:enable /failure:enable
:::: Security Group Management
auditpol /set /category:{0CCE9237-69AE-11D9-BED3-505054503030} /success:enable /failure:enable
:::: User Account Management
auditpol /set /category:{0CCE9235-69AE-11D9-BED3-505054503030} /success:enable /failure:enable
```

Great work anyway! ;-)
Greetings from Germany,
Lasse

**Comment by YamatoSecurity** [comment]
@LasseKrache Thank you so much for pointing this out! Yes, all of them should have been `/subcategory`, so I fixed the script.

**Comment by YamatoSecurity** [comment]
I'm going to mark this as fixed. Please let me know if there are any other issues.
