### ISSUE TITLE
Inconsistence

### ISSUE THREAD

**Issue by LasseKrache** [Yamato-Security/EnableWindowsLogSettings#9]
Hello,

I have noticed the following "inconsistence" in the batch file:

```
:::: Detailed File Share (disabled due to noise)
auditpol /set /subcategory:{0CCE9244-69AE-11D9-BED3-505054503030} /success:enable /failure:enable

:::: Filtering Platform Packet Drop (disabled due to noise)
auditpol /set /subcategory:{0CCE9225-69AE-11D9-BED3-505054503030} /success:enable /failure:enable

:::: Registry (currently disabled due to noise)
auditpol /set /subcategory:{0CCE921E-69AE-11D9-BED3-505054503030} /success:enable /failure:enable

:::: MPSSVC Rule-Level Policy Change (currently disabled while testing)
auditpol /set /subcategory:{0CCE9232-69AE-11D9-BED3-505054503030} /success:enable /failure:enable
```

So maybe you just forgot to disable the command or to modify the comment. 
These are not "issues" of course, but I just wanted to report it.

Thank you VERY MUCH for this amazing script!
Lasse

**Comment by YamatoSecurity** [comment]
@LasseKrache  Thank you so much for letting me know! I am not sure why I missed that. I will fix it tomorrow.

**Comment by YamatoSecurity** [comment]
@LasseKrache I fixed this in https://github.com/Yamato-Security/EnableWindowsLogSettings/pull/10
If this looks good to you, I will close the issue.

**Comment by LasseKrache** [comment]
Looks good!
Thank you!
